version: "2.4"

services:
  database:
    image: mariadb:10.3.22
    environment:
      MYSQL_DATABASE: ${DB_NAME:-drupal}
      MYSQL_USER: ${DB_USER:-drupal}
      MYSQL_PASSWORD: ${DB_PASSWORD:-dbpassword}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-dbpassword}
    volumes:
      - database-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]

  drupal:
    image: registry.gitlab.com/calincs/cwrc/orlando-cambridge/master:latest
    depends_on:
      database:
        condition: service_healthy
    ports:
      - 80:8080
    environment:
      APP_NAME: ${APP_NAME:-orlando}
      APP_ROOT: ${APP_ROOT:-/var/www/app}
      APP_ACCOUNT_NAME: ${DRUPAL_USER_NAME:-orlando}
      APP_ACCOUNT_MAIL: ${DRUPAL_USER_EMAIL:-orlando@example.com}
      APP_ACCOUNT_PASS: ${APP_ACCOUNT_PASS:-orlando}
      DB_NAME: ${DB_NAME:-drupal}
      DB_USER: ${DB_USER:-drupal}
      DB_PASSWORD: ${DB_PASSWORD:-dbpassword}
      DB_HOST: database
      DB_PORT: ${DB_PORT:-3306}
      DB_DRIVER: ${DB_DRIVER:-mysql}
      DRUSH_OPTIONS_URI: "${DRUPAL_LOCAL_URL:-localhost:8000}"
      DRUPAL_HASH_SALT: ${DRUPAL_HASH_SALT:-tfvQNpDFG2CjY9WHGNgFqC3eoMjyg5pZdGMQ74zjmnIoe0bi8F3hUvBWnGFIAM3nnj2iWA}
      NGINX_LISTEN_PORT: "8080"
      AUTO_INSTALL: "true"
      BASEX_ROOT_USER: ${BASEX_ROOT_USER:-admin}
      BASEX_ROOT_PASSWORD: ${BASEX_ROOT_PASSWORD:-admin}
      BASEX_USER: ${BASEX_USER:-orlando}
      BASEX_DATABASE: ${BASEX_DATABASE:-orlando}
      BASEX_PASSWORD: ${BASEX_PASSWORD:-orlando}
    volumes:
      - drupal-files:${FILES_DIR:-/mnt/files}

  basex:
    image: registry.gitlab.com/calincs/cwrc/orlando-basex:latest
    environment:
      BASEX_ROOT_USER: ${BASEX_ROOT_USER:-admin}
      BASEX_ROOT_PASSWORD: ${BASEX_ROOT_PASSWORD:-admin}
      BASEX_USER: ${BASEX_USER:-orlando}
      BASEX_DATABASE: ${BASEX_DATABASE:-orlando}
      BASEX_PASSWORD: ${BASEX_PASSWORD:-orlando}
    volumes:
      - basex-data:/srv/basex/data
      - basex-repo:/srv/basex/repo
      - basex-webapp:/srv/basex/webapp

volumes:
  basex-data:
  basex-repo:
  basex-webapp:
  database-data:
  drupal-files:
